/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{html,ts}',
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Fraunces"', 'ui-serif', 'Georgia', 'serif'],
        sans: ['"Manrope"', 'system-ui', '-apple-system', 'sans-serif'],
      },
      borderRadius: {
        lg: '0.5rem',
        md: '0.375rem',
        sm: '0.25rem',
      },
      boxShadow: {
        stripe: 'inset 3px 0 0 0 var(--tw-stripe-color, currentColor)',
      },
    },
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {
        barber: {
          'primary': '#A9762F',
          'primary-content': '#F6F1E7',
          'secondary': '#7A2E2E',
          'secondary-content': '#F6F1E7',
          'accent': '#3F5744',
          'accent-content': '#F6F1E7',
          'neutral': '#1B1815',
          'neutral-content': '#F6F1E7',
          'base-100': '#FBF8F2',
          'base-200': '#F2ECE0',
          'base-300': '#E4DAC6',
          'base-content': '#1B1815',
          'info': '#3B5B73',
          'info-content': '#F6F1E7',
          'success': '#3F5744',
          'success-content': '#F6F1E7',
          'warning': '#A9762F',
          'warning-content': '#1B1815',
          'error': '#7A2E2E',
          'error-content': '#F6F1E7',
          '--rounded-box': '0.75rem',
          '--rounded-btn': '0.375rem',
          '--rounded-badge': '0.25rem',
        },
      },
      {
        'barber-noche': {
          'primary': '#C79A4E',
          'primary-content': '#17140F',
          'secondary': '#C2645F',
          'secondary-content': '#17140F',
          'accent': '#7DA085',
          'accent-content': '#17140F',
          'neutral': '#0E0C09',
          'neutral-content': '#EDE6D6',
          'base-100': '#17140F',
          'base-200': '#211C15',
          'base-300': '#2E2719',
          'base-content': '#EDE6D6',
          'info': '#7FA6C4',
          'info-content': '#17140F',
          'success': '#7DA085',
          'success-content': '#17140F',
          'warning': '#C79A4E',
          'warning-content': '#17140F',
          'error': '#C2645F',
          'error-content': '#17140F',
          '--rounded-box': '0.75rem',
          '--rounded-btn': '0.375rem',
          '--rounded-badge': '0.25rem',
        },
      },
    ],
    base: true,
    styled: true,
    utils: true,
  },
};
